name: Washington Wellness
title: Washing Wellness
description: Personal Trainer Marcus Washington
paginate: 5
paginate_path: "page:num"
baseurl: ''

email: kmwshington47@gmail.com
twitter: kmwshington
facebook: 1washington.wellness
instagram: kmwashington1
youtube: UCi8YPAciDHRKuDD982ObCVA
linkedin: marcus-washington-47b9a390
disqus_shortname: washingtonwellness

sass:
  style: compressed

gems:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-sitemap
 - jekyll-seo-tag
 - jemoji
